---
- hosts: myWebServers
  become: yes
  tasks:
  - name: ping all nodes
    ping:
  - name: Install apache 2 on nodes
    apt:
     name: apache2
     state: present
    when: ansible_os_family=="Debian"

  - name: I want to start apache server
    service:
     name: apache2
     state: started
    when: ansible_os_family=="Debian"
  
  - name: I want to install apache2 on Redhat
    yum:
     name: httpd
     state: present
    when: ansible_os_family=="RedHat"

  - name: I want to start webserver on Redhat
    service:
     name: httpd
     state: started
    when: ansible_os_family=="RedHat"
